openapi: 3.0.3
info:
  title: Payment Processing API
  version: 1.0.0
  description: API for processing payments
paths:
  /api/v1/payments/:
    get:
      operationId: v1_payments_retrieve
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
          description: ''
    post:
      operationId: v1_payments_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payment'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
          description: ''
  /api/v1/payments/{payment_id}/:
    get:
      operationId: v1_payments_retrieve_2
      parameters:
      - in: path
        name: payment_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentStatus'
          description: ''
components:
  schemas:
    Payment:
      type: object
      properties:
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        customer_email:
          type: string
          format: email
          maxLength: 254
        customer_name:
          type: string
          maxLength: 100
      required:
      - amount
      - customer_email
      - customer_name
    PaymentStatus:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        customer_email:
          type: string
          format: email
          maxLength: 254
        customer_name:
          type: string
          maxLength: 100
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - amount
      - customer_email
      - customer_name
      - id
      - updated_at
    StatusEnum:
      enum:
      - PENDING
      - COMPLETED
      - FAILED
      type: string
      description: |-
        * `PENDING` - Pending
        * `COMPLETED` - Completed
        * `FAILED` - Failed
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
